# Basic cutout search parameters
####DEFAULTS######
cutouts:
    # search radius around the specified source location in arcmin.
    # The cutouts will be of maximum width and height of 2*radius
    radius: 1

    #custom filters in brackets
    surveys:
        #- FIRST
        #- NVSS
        - VLASS
        - WISE[W1]
        - PanSTARRS[i]
        - SDSS[g,r,i]

    # group by MOSAIC, NONE, or DATE-OBS, default is NONE (no grouping)
    group_by: NONE

# Processing output parameters
configuration:
    # folder to put FITS output data into further separated by Survey name folder
    output: data_out/

    # overwrite existing files on download
    overwrite: True

    # flush old data files for each survey before downloading (superceeds overwrite)
    flush: False
